services:
  backend:
    build:
      context: backend
    volumes:
      - ./backend/src:/backend/src
      - /backend/node_modules
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  portal:
    build:
      context: portal
    restart: always
    ports:
      - "127.0.0.1:5173:5173"
      
  server:
    image: ghcr.io/collabora/whisperlive-cpu:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./model:/root/.cache/
    stdin_open: true
    tty: true

