services:
  backend:
    build:
      context: backend
    volumes:
      - ./backend/src:/backend/src
      - /backend/node_modules
    env_file: .env
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  web:
    build:
      context: .
      target: web
    command: nginx -g 'daemon off;'
    restart: always
    ports:
      - "127.0.0.1:9000:80"
    depends_on:
      - backend

  server:
    image: ghcr.io/collabora/whisperlive-cpu:latest
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./model:/root/.cache/
    stdin_open: true
    tty: true

